[nats]
broker-url = "nats-server"
broker-port = 4222

[rotator]
type = "dummy"
name = "WARC Yagi"
has-azimuth = true
has-elevation = false
pollingrate = "100ms"
azimuth-min = 0
azimuth-max = 360
azimuth-stop = 170